function F = ensembles_on_traces(E,exp,STIMSAMP,istage)
% ensembles_on_traces(E,exp,STIMSAMP,istage) - visualizes df/f traces of the ROIs
% that are a part of detected ensembles
%
%   INPUTS:
%       E - ensemble struct, generated by ensembles_on_raster
%       exp - experiment object
%       STIMSAMP - stimuli-based struct
%       istage - stage ID
%
%   OUTPUTS:
%
%part of ZENITH

Nens = numel(E);
Nrecs = STIMSAMP.full_xl/STIMSAMP.full_s;
for ie = 1:Nens
    unROIs = [];
    unsamples = [];
    Npairs = numel(E(ie).pair);
    for ipair = 1:Npairs
        unROIs = unique([unROIs;E(ie).pair(ipair).rois]);
        unsamples = unique([unsamples,E(ie).pair(ipair).samples]);
    end
    h = waitbar(0,['stitching ROIs for ensemble ', num2str(ie)]);
    for iROI = 1:numel(unROIs)
        waitbar(iROI/numel(unROIs))
        ST(iROI,:) = stitch(exp,unROIs(iROI),istage,'dff');
    end
    close(h)
    
    yl = [0, 2*numel(ST)+10];
    F(ie) = figure;
    affectedrecs = [];
    for irec = 1:Nrecs
        STIM(irec).samps = STIMSAMP.stim_on+STIMSAMP.full_s*(irec-1):STIMSAMP.stim_off+STIMSAMP.full_s*(irec-1);
        if sum(ismember(STIM(irec).samps,unsamples))> 1
            affectedrecs = unique([affectedrecs,irec]);
        end
    end
    for irec = 1:Nrecs
        if ismember(irec,affectedrecs)
            col = [0.302 0.749 0.9294];
        else
            col = [0.5 0.5 0.5];
        end
        patch([STIMSAMP.stim_on+STIMSAMP.full_s*(irec-1), STIMSAMP.stim_off+STIMSAMP.full_s*(irec-1),...
            STIMSAMP.stim_off+STIMSAMP.full_s*(irec-1),STIMSAMP.stim_on+STIMSAMP.full_s*(irec-1)],...
            [yl(1),yl(1),yl(2),yl(2)],col,'EdgeColor','None','FaceAlpha',0.5);
    end
    hold on
    for ist = 1: numel(ST)
        D(ist,:) = ST(ist).data+(ist-1)*2;
    end
    plot(D','k-');
%     for ipair = 1:Npairs
%         rois = E(ie).pair(ipair).rois;
%         goodrois_idx = ismember(unROIs,rois);
%         samples = E(ie).pair(ipair).samples;
%         for isample = 1:numel(samples)
%             dd = D(goodrois_idx,samples(isample));
%             plot(samples(isample),dd,'r.');
%         end
%     end
clear unROIs unsamples ST affectedrecs STIM D
end
